services:
    web:
        build: .
        ports:
        - "8080:8080"
        volumes:
            -   ./src/main/resources:/config/
        depends_on:
            db:
                condition: service_healthy
    db:
        image: "mysql:latest"
        ports:
        - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "Alexsql1512"
            MYSQL_DATABASE: "library"
        healthcheck:
            test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost", "-pAlexsql1512" ]
            interval: 10s
            timeout: 20s
            retries: 10