services:
    web:
        build: .
        ports:
        - "8080:8080"
    db:
        image: "mysql:5.7"
        ports:
        - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "Alexsql1512"
            MYSQL_DATABASE: "library"