spring:
    application:
        name: "library"
    datasource:
        url: jdbc:mysql://db:3306/library
        username: root
        password: Alexsql1512
    jpa:
        hibernate:
            ddl-auto: update

server:
    port: 8080



